spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/it355_projekat}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:ognjen123}
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  servlet:
    context-path: /api
